# Generated by Django 3.1.2 on 2022-03-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_addresses'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addresses',
            unique_together={('zip_code', 'prefecture', 'address')},
        ),
    ]
